#!/bin/bash
#Split up the tmux window for IDE develop environment
tmux split-window -v -p 50
tmux split-window -h -p 66
tmux split-window -h -p 50
tmux select-pane -t 0
tmux split-window -h -p 66
tmux split-window -h -p 50
